using AutoMapper;
using ServiceManagerApi.Data;
using ServiceManagerApi.Dtos.Compartments;
using ServiceManagerApi.Dtos.CycleDetails;
using ServiceManagerApi.Dtos.Equipments;
using ServiceManagerApi.Dtos.FaultEntry;
using ServiceManagerApi.Dtos.FleetSchedule;
using ServiceManagerApi.Dtos.FuelIntake;
using ServiceManagerApi.Dtos.GroundEngagingTools;
using ServiceManagerApi.Dtos.Groups;
using ServiceManagerApi.Dtos.HaulerOperator;
using ServiceManagerApi.Dtos.HoursEntries;
using ServiceManagerApi.Dtos.HoursEntriesTemp;
using ServiceManagerApi.Dtos.Items;
using ServiceManagerApi.Dtos.ItemValue;
using ServiceManagerApi.Dtos.LoaderOperator;
using ServiceManagerApi.Dtos.LubeBrands;
using ServiceManagerApi.Dtos.LubeConfigs;
using ServiceManagerApi.Dtos.LubeEntry;
using ServiceManagerApi.Dtos.LubeGrades;
using ServiceManagerApi.Dtos.Model;
using ServiceManagerApi.Dtos.PlannedOutput;
using ServiceManagerApi.Dtos.ProdProcessedMaterial;
using ServiceManagerApi.Dtos.ProdRawMaterial;
using ServiceManagerApi.Dtos.ProductionActivity;
using ServiceManagerApi.Dtos.ProductionDestination;
using ServiceManagerApi.Dtos.ProductionMineArea;
using ServiceManagerApi.Dtos.ProductionOrigin;
using ServiceManagerApi.Dtos.ProductionShift;
using ServiceManagerApi.Dtos.ProHaulerUnits;
using ServiceManagerApi.Dtos.ProLoaderUnits;
using ServiceManagerApi.Dtos.RefillTypes;
using ServiceManagerApi.Dtos.Resolution;
using ServiceManagerApi.Dtos.ResolutionTypes;
using ServiceManagerApi.Dtos.ScheduleTransactionsDto;
using ServiceManagerApi.Dtos.Sections;
using ServiceManagerApi.Dtos.Services;

namespace ServiceManagerApi.Helpers;

public class AutoMappingProfiles : Profile
{
  public AutoMappingProfiles()
  {
    CreateMap<RefillTypePostDto, RefillType>();
    CreateMap<ItemsPostDto, Item>();
    CreateMap<ItemValuePostDto, ItemValue>();
    CreateMap<GroupsPostDto, Group>();
    CreateMap<SectionPostDto, Section>();
    CreateMap<ServicePostDto, Service>();
    CreateMap<LubeBrandPostDto, LubeBrand>();
    CreateMap<LubeGradePostDto, LubeGrade>();
    CreateMap<LubeConfigPostDto, LubeConfig>();
    CreateMap<LubeEntryPostDto, LubeEntry>();
    CreateMap<CompartmentPostDto, Compartment>();
    CreateMap<ResolutionPostDto, Resolution>();
    CreateMap<HoursEntriesPostDto, HoursEntry>();
    CreateMap<HoursEntriesPutDto, HoursEntry>();
    CreateMap<HoursEntriesTempPostDto, HoursEntryTemp>();
    CreateMap<HoursEntriesTempPutDto, HoursEntryTemp>();
    CreateMap<ResolutionTypePostDto, ResolutionType>();
    CreateMap<ProductionActivityPostDto, ProductionActivity>();
    CreateMap<ProductionMineAreaPostDto, ProductionMineArea>();
    CreateMap<ProductionShiftPostDto, ProductionShift>();
    CreateMap<GroundEngagingToolsPostDto, GroundEngTool>();
    CreateMap<GroundEngagingToolsPutDto, GroundEngTool>();
    CreateMap<ModelCreateDto, Model>();
    CreateMap<HaulerOperatorPostDto, HaulerOperator>();
    CreateMap<LoaderOperatorPostDto, LoaderOperator>();
    CreateMap<ProductionOriginPostDto, ProductionOrigin>();
    CreateMap<ProdRawMaterialPostDto, ProdRawMaterial>();
    CreateMap<ProductionDestinationPostDto, ProductionDestination>();
    CreateMap<ProdProcessedMaterialPostDto, ProdProcessedMaterial>();
    CreateMap<ScheduleTransactionsPostDto, ScheduleTransaction>();
    CreateMap<ProLoaderUnitPostDto, ProloaderUnit>();
    CreateMap<ProHaulerUnitPostDto, ProhaulerUnit>();
    CreateMap<PlannedOutputPostDto, PlannedOutput>();
    CreateMap<CycleDetailPostDto, CycleDetail>();
    CreateMap<FaultEntryPostDto, FaultEntry>();
    CreateMap<EquipmentPostDto, Equipment>();
    CreateMap<FleetSchedulePostDto, FleetSchedule>();
    CreateMap<ProdPumpPostDto, ProductionPump>();
    CreateMap<FuelIntakePostDto, ProFuelIntake>();
    CreateMap<ProActivityDetailsPostDto, ProActivityDetail>();
  }
}